Repository RedHatInsights/insights-chrome, pull requests merged in 2020-10, with the labels that each got.

#996 Added OUIA props to Sidenav
  src/js/App/Sidenav/AppSwitcher.js
  src/js/App/Sidenav/Navigation.js
  src/js/App/Sidenav/__snapshots__/AppSwitcher.test.js.snap
  src/js/App/Sidenav/__snapshots__/Navigation.test.js.snap
Labels: don't merge, on hold

#997 Fix permissions gate by changing it to object
  src/js/rbac/fetchPermissions.js
Labels: bug

#1001 Disable permission cache
  src/js/rbac/fetchPermissions.js
Labels: bug

#1012 Fix 404 spinner, skeleton, conditional filter.
  package-lock.json
  package.json
  src/sass/chrome.scss
Labels: bug

#1033 App switcher updates
  src/js/App/Sidenav/AppSwitcher.js
  src/js/App/Sidenav/AppSwitcher.scss
Labels: enhancement

#1031 Log insights.chrome.navigation usage
  README.md
Labels: technical debt
