Repository RedHatInsights/insights-chrome, pull requests merged in 2020-09, with the labels that each got.

#948 Optimize build speed
  config/webpack.config.js
  config/webpack.plugins.js
  package-lock.json
  package.json
Labels: technical debt

#942 Navigation and avatar changes
  src/js/App/Header/HeaderTests/__snapshots__/Tools.test.js.snap
  src/js/App/Header/HeaderTests/__snapshots__/UserToggle.test.js.snap
  src/js/App/Header/Tools.js
  src/js/App/Header/UserIcon.js
  src/js/App/Header/UserIcon.scss
  src/js/App/Header/UserToggle.js
  src/js/App/Sidenav/Navigation.js
  src/js/App/Sidenav/__snapshots__/Navigation.test.js.snap
Labels: on hold

#958 Fix navigation text alignment.
  src/js/App/Sidenav/Navigation.js
  src/js/App/Sidenav/__snapshots__/Navigation.test.js.snap
  src/sass/chrome.scss
Labels: bug

#975 Guard and cache fetchPermission chrome API.
  src/js/entry.js
  src/js/jwt/__mocks__/jwt.js
  src/js/rbac/fetchPermissions.js
  src/js/rbac/fetchPermissions.test.js
Labels: enhancement

#979 Fix undefined session_state when creating permission cache.
  src/js/entry.js
  src/js/rbac/fetchPermissions.js
Labels: bug

#983 Make chrome a closure
  config/setupTests.js
  src/js/chrome.js
  src/js/chrome.test.js
  src/js/chrome/create-chrome.js
  src/js/chrome/create-chrome.test.js
  src/js/chrome/entry.js
  src/js/chrome/initialize-jwt.js
  src/js/chrome/initialize-jwt.test.js
  src/js/chrome/iqeEnablement.js
  src/js/nav/__mocks__/globalNav.js
  src/js/nav/__mocks__/sourceOfTruth.js
  src/js/rbac/__mocks__/fetchPermissions.js
  src/js/rbac/fetchPermissions.js
  src/js/rbac/fetchPermissions.test.js
Labels: enhancement

#985 Trigger _satellite.pageBottom event on location change.
  src/js/chrome.js
  src/js/url-observer.js
  src/pug/after.pug
Labels: enhancement

#991 Allow getUserPermission cache bypass.
  src/js/chrome/create-chrome.js
  src/js/rbac/fetchPermissions.js
Labels: bug

#992 Update frontend components dependencies.
  package-lock.json
  package.json
Labels: dependencies, technical debt

#990 Move chrome instance initialization to try catch block.
  src/js/chrome/initialize-jwt.js
Labels: bug

#994 Downgrade pf version.
  package-lock.json
  package.json
  src/js/App/Header/HeaderTests/__snapshots__/Brand.test.js.snap
  src/js/App/Header/HeaderTests/__snapshots__/Header.test.js.snap
  src/js/App/Header/HeaderTests/__snapshots__/UserToggle.test.js.snap
  src/js/App/Sidenav/__snapshots__/AppSwitcher.test.js.snap
  src/js/App/Sidenav/__snapshots__/Navigation.test.js.snap
Labels: bug
