Repository RedHatInsights/insights-chrome, pull requests merged in 2021-04, with the labels that each got.

#1318 Fix: invalid/missting prop types on dom elements
  src/js/App/Sidenav/BetaInfoModal.js
  src/js/App/Sidenav/Loader.js
Labels: technical debt

#1332 Update inventory components.
  package-lock.json
  package.json
Labels: bug

#1339 Add stage.foo to consts
  src/js/jwt/constants.js
Labels: on hold

#1381 [prod stable] fix documentation beta badge and do not show on beta
  src/js/App/Sidenav/NavigationItem.js
Labels: prod-stable push
