Repository RedHatInsights/insights-chrome, pull requests merged in 2021-01, with the labels that each got.

#1101 Add app filter
  .travis/custom_release.sh
  src/js/App/Header/AppFilter.js
  src/js/App/Header/AppFilter.scss
  src/js/App/Header/Header.js
  src/js/nav/globalNav.js
Labels: don't merge

#1109 Sync chrome 2 branch with master
  README.md
  docs/analytics.md
  docs/api.md
  docs/debugging.md
  docs/errorHandling.md
  docs/navigation.md
  docs/usage.md
  package-lock.json
  package.json
  src/js/App/GlobalFilter/GlobalFilter.js
  src/js/App/GlobalFilter/constants.js
  src/js/App/GlobalFilter/constants.test.js
  src/js/App/Header/HeaderTests/__snapshots__/Tools.test.js.snap
  src/js/App/Header/Tools.js
  src/js/App/Sidenav/AppSwitcher.js
  src/js/App/Sidenav/Navigation.js
  src/js/analytics.js
  src/js/chrome/create-chrome.js
  src/js/chrome/entry.js
  src/js/consts.js
  src/js/consts.test.js
  src/js/createCase.js
  src/js/jwt/constants.js
  src/js/jwt/insights/url.js
  src/js/remediations/index.js
  src/js/url-observer.js
  src/js/utils.js
  src/js/utils/cache.js
Labels: C2

#1111 Update scalprum to latest version.
  package-lock.json
  package.json
Labels: C2

#1110 Add temporary chrome2 flag on window.
  src/pug/templates/head-block.pug
Labels: C2

#1114 [Prod-stable] Point cog to MUA
  src/js/App/Header/HeaderTests/__snapshots__/Tools.test.js.snap
  src/js/App/Header/Tools.js
Labels: prod-stable push

#1125 update pendo on prod-stable to use new config
  src/js/analytics.js
Labels: prod-stable push

#1121 Do not load nav config for unauthed user.
  src/js/chrome/create-chrome.js
Labels: bug, don't merge
