Repository RedHatInsights/insights-chrome, pull requests merged in 2021-02, with the labels that each got.

#1158 Fix: hide hamburger toggle in unathed page.
  src/js/redux/reducers.js
Labels: bug

#1177 Fix: missing chrome 2 flag.
  src/js/chrome/entry.js
Labels: bug

#1178 Update chrome dependencies
  config/webpack.config.js
  package-lock.json
  package.json
  src/js/App/GlobalFilter/GlobalFilter.js
  src/js/App/GlobalFilter/constants.js
  src/js/App/GlobalFilter/constants.test.js
  src/js/App/GlobalFilter/tagsApi.js
  src/js/App/Header/HeaderTests/__snapshots__/InsightsAbout.test.js.snap
  src/js/App/Header/HeaderTests/__snapshots__/Login.test.js.snap
  src/js/App/Header/HeaderTests/__snapshots__/LogoutAlert.test.js.snap
  src/js/App/Header/HeaderTests/__snapshots__/ToolbarToggle.test.js.snap
  src/js/App/Header/HeaderTests/__snapshots__/UserToggle.test.js.snap
  src/js/App/Header/InsightsAbout.scss
  src/js/App/Sidenav/__snapshots__/AppSwitcher.test.js.snap
  src/js/App/Sidenav/__snapshots__/Navigation.test.js.snap
  src/js/App/Sidenav/__snapshots__/NavigationItem.test.js.snap
  src/js/App/Sidenav/__snapshots__/SideNav.test.js.snap
  src/js/App/__snapshots__/RootApp.test.js.snap
  src/js/consts.js
  src/js/inventory/details.js
  src/js/inventory/inventoryStyles.js
  src/js/inventory/modules/AsyncInventory.js
  src/js/nav/globalNav.js
  src/js/nav/globalNav.test.js
  src/js/redux-config.js
  src/js/redux/index.js
  src/js/remediations/index.js
  src/js/utils/useGlobalNav.js
  src/sass/chrome.scss
Labels: dependencies

#1184 Update scalprum dependency
  package-lock.json
  package.json
Labels: C2, bug

#1183 Update layout to use react PF page layout.
  src/js/App/Header/Brand.js
  src/js/App/Header/Header.js
  src/js/App/Header/HeaderTests/Brand.test.js
  src/js/App/Header/HeaderTests/Header.test.js
  src/js/App/Header/HeaderTests/__snapshots__/Brand.test.js.snap
  src/js/App/Header/HeaderTests/__snapshots__/Header.test.js.snap
  src/js/App/Header/Login.js
  src/js/App/Header/UnAuthtedHeader.js
  src/js/App/RootApp.js
  src/js/App/Sidenav/SideNav.js
  src/js/App/__snapshots__/RootApp.test.js.snap
  src/js/chrome.test.js
  src/js/redux/action-types.js
  src/js/redux/index.js
  src/js/redux/reducers.js
Labels: C2, bug

#1189 Fix: rendering of non chrome 2 apps
  src/js/App/RootApp.js
Labels: C2, bug

#1190 Fix: landing page global nav undefined.
  src/js/redux/reducers.js
Labels: C2, bug

#1191 Fix: catch click event on app filter click
  src/js/App/Header/AppFilter.js
Labels: C2, bug

#1195 Memoize page root
  src/js/App/RootApp.js
Labels: C2, bug

#1180 Always show either App filter or Switcher
  src/js/App/Sidenav/SideNav.js
Labels: cherry-pick

#1198 Fix: use div as nav logo root element
  src/js/App/Header/AppFilter.js
  src/js/App/Header/Header.js
  src/js/App/Header/HeaderTests/__snapshots__/Header.test.js.snap
  src/js/App/RootApp.js
  src/js/App/__snapshots__/RootApp.test.js.snap
  src/sass/chrome.scss
Labels: C2, bug

#1207 Fix: settings beta link
  src/js/App/Header/ToolbarToggle.js
  src/js/App/Header/Tools.js
Labels: bug

#1213 Fix: browser back button nav
  src/js/App/Sidenav/Navigation.js
Labels: C2, bug

#1206 Catch undefined apps.
  src/js/App/Header/AppFilter.js
  src/js/utils/useGlobalNav.js
Labels: bug

#1219 Fix: wait with module search after user is initialized.
  src/js/App/RootApp.js
Labels: C2, bug

#1226 Fix ERR_UNKNOWN_URL_SCHEME source map warnings
  config/webpack.config.js
  config/webpack.plugins.js
Labels: technical debt

#1231 Clean up errors
  src/js/App/GlobalFilter/GlobalFilter.js
  src/js/App/Header/AppFilter.js
  src/js/App/Header/ToolbarToggle.js
  src/js/App/Sidenav/Navigation.js
  src/js/App/Sidenav/SectionNav.js
Labels: technical debt

#1228 Use router location to mark landing page.
  src/js/App/RootApp.js
Labels: C2, bug

#1230 Add change document title API.
  docs/api.md
  src/js/chrome/entry.js
  src/js/utils.js
Labels: C2
