Repository RedHatInsights/insights-chrome, pull requests merged in 2022-05, with the labels that each got.

#1873 [prod-beta] Update build
  build_deploy.sh
  frontend.yml
  package-lock.json
  package.json
  pr_check.sh
Labels: dependencies

#1867 Added darkmode support
  src/js/App/Header/Tools.js
  src/js/debugFunctions.js
  src/sass/chrome.scss
Labels: post summit

#1897 add ability to send activation request
  src/js/App/Activation/Activation.js
  src/js/App/Activation/index.js
  src/js/App/Header/Header.js
Labels: NeedsProd
