Repository RedHatInsights/insights-chrome, pull requests merged in 2022-04, with the labels that each got.

#1798 TS Migration
  package-lock.json
  package.json
  src/js/jwt/constants.ts
  src/js/jwt/jwt.unit.test.js
  src/js/sentry.ts
  src/js/types.d.ts
  src/js/types.ts
  src/js/url-observer.ts
  src/js/utils.test.js
  src/js/utils.ts
Labels: technical debt

#1846 Update PF version
  package-lock.json
  package.json
  src/js/App/Header/Header.scss
Labels: bug, dependencies

#1862 Use fresh and stale filter for stalness
  src/js/App/GlobalFilter/tagsApi.js
Labels: bug

#1864 Gracefully handle quickstarts progress XHR failure
  src/js/App/QuickStart/useQuickstartsStates.js
Labels: bug

#1863 Update PF dependencies
  config/webpack.plugins.js
  docs/migrationGuide.md
  package-lock.json
  package.json
  src/js/App/QuickStart/helpTopicDataMock.json
  src/js/App/QuickStart/helpTopicDataMock.ts
  src/js/App/QuickStart/useHelpTopicState.test.ts
  src/js/App/QuickStart/useHelpTopicState.ts
Labels: dependencies

#1870 Bump quickstarts version
  package-lock.json
  package.json
Labels: dependencies

#1872 [stable] update build
  package-lock.json
  package.json
Labels: dependencies
