Repository RedHatInsights/insights-chrome, pull requests merged in 2022-06, with the labels that each got.

#1707 Use webpack to build all assets
  README.md
  config/image-null-loader.js
  config/patternfly-react-externals.js
  config/patternfly-table-externals.js
  config/pf-react-core-externals.js
  config/pf-react-icons-externals.js
  config/react-external.js
  config/react-redux-external.js
  config/react-router-dom-externals.js
  config/webpack.config.js
  config/webpack.plugins.js
  package-lock.json
  package.json
  scripts/build-pug.js
  scripts/build-sass.js
  src/js/chrome.js
  src/js/externalDependencies.js
  src/pug/after.pug
  src/pug/body.pug
  src/pug/globalNav.pug
  src/pug/head-staging.pug
  src/pug/head.pug
  src/pug/header.pug
  src/pug/imageFilter.pug
  src/pug/landing-header.pug
  src/pug/landing-nav.pug
  src/pug/landing.pug
  src/pug/sidebar-new.pug
  src/pug/sidebar.pug
  src/pug/slices/hamburger-hidden.pug
  src/pug/slices/hamburger.pug
  src/pug/slices/logo.pug
  src/pug/slices/mobileKebab.pug
  src/pug/slices/tools.pug
  src/pug/slices/userDropdown.pug
  src/pug/templates/brand-block.pug
  src/pug/templates/brand-noHamburger-block.pug
  src/pug/templates/head-block.pug
  src/pug/templates/index.pug
  src/pug/templates/tools-block.pug
Labels: technical debt

#1916 Fix font awesome asset loading.
  config/webpack.config.js
  package-lock.json
  package.json
Labels: bug

#1917 Preserve sso-url.js output chunk name.
  config/webpack.config.js
Labels: bug

#1853 Migrate JWT to TS :haircut_man:
  config/setupTests.js
  package-lock.json
  package.json
  src/js/analytics.test.js
  src/js/jwt/Priv.js
  src/js/jwt/Priv.ts
  src/js/jwt/__mocks__/@redhat-cloud-services/keycloak-js.js
  src/js/jwt/__mocks__/jwt.js
  src/js/jwt/insights/__mocks__/entitlements.ts
  src/js/jwt/insights/entitlements.ts
  src/js/jwt/insights/url.ts
  src/js/jwt/insights/user.ts
  src/js/jwt/insights/user.unit.test.js
  src/js/jwt/jwt.ts
  src/js/jwt/jwt.unit.test.ts
  src/js/jwt/logger.ts
  src/js/redux/action-types.ts
  src/js/utils/cache.test.js
  src/js/utils/cache.test.ts
  src/js/utils/cache.ts
Labels: technical debt

#1937 adding more urls for activation requests
  src/js/App/Header/Header.js
  src/js/consts.ts
Labels: NeedsProd
