Repository RedHatInsights/insights-chrome, pull requests merged in 2024-06, with the labels that each got.

#2857 Migrate notifications reducer to Jotai
  cypress/component/NotificationDrawer/NotificationDrawer.cy.tsx
  src/components/Header/Tools.tsx
  src/components/NotificationsDrawer/DrawerPanelContent.test.tsx
  src/components/NotificationsDrawer/DrawerPanelContent.tsx
  src/components/NotificationsDrawer/NotificationItem.tsx
  src/components/RootApp/ScalprumRoot.tsx
  src/hooks/useChromeServiceEvents.ts
  src/layouts/DefaultLayout.tsx
  src/redux/action-types.ts
  src/redux/actions.ts
  src/redux/chromeReducers.ts
  src/redux/index.ts
  src/redux/store.d.ts
  src/state/atoms/notificationDrawerAtom.ts
Labels: technical debt

#2870 Update patternfly quickstarts
  package-lock.json
  package.json
Labels: dependencies

#2873 Duplicate FF context before updating preview env.
  src/state/atoms/releaseAtom.ts
Labels: bug

#2876 Update minor dependecy versions.
  cypress/component/NotificationDrawer/NotificationDrawer.cy.tsx
  jest.config.js
  package-lock.json
  package.json
  src/auth/initializeAccessRequestCookies.test.ts
  src/components/NotificationsDrawer/DrawerPanelContent.tsx
  src/redux/redux-config.ts
Labels: dependencies, technical debt
